### PR TITLE
re-introduce PromisedScene into main repo

### PR DESCRIPTION
**Pull request by Ch00nassid**
LeadWolfs most recent re-write is pretty secure for release into the main repository

### CODE REVIEW

**Comment by Ch00nassid** [comment]
don't know how to do this....lol

**Comment by Ch00nassid** [comment]
Can someone help me resolve the conflicts in the Readme?  I can't seem update my repo with the out dated files...

**Comment by leadwolf** [comment]
Will take a look this week. Did you update the logger already ?

**Comment by Ch00nassid** [comment]
No, I didn't look at the logger -- I think there are other pornvault plugin references that need to be updated that I don't have (import of 'plugins.ts' from the types folder?).

**Comment by boi123212321** [comment]
Context needs to be updated https://github.com/porn-vault/porn-vault-plugins/issues/102

**Comment by Ch00nassid** [comment]
I think i might need to work with @leadwolf on this, I'm not really sure I know what i am doing to fix everything with my forked branch.  I thought that the main porn-plugins branch would have updated contexts and then i would just merge with the upstream like i did previously?

might need some help with this one.

**Review by leadwolf — APPROVED** [review]

**Pull request merged**
